version: "3.9"

services:

  sge.postgres:
    image: postgres:latest
    container_name: sge_postgres
    environment:
      POSTGRES_DB: sgedb
      POSTGRES_USER: sgeuser
      POSTGRES_PASSWORD: sgepassword
    ports:
      - "5432:5432"
    networks:
      - sge_network

  sge.api:
    build:
      context: .
      dockerfile: ./SGE.API/Dockerfile
    container_name: sge_api
    image: sge.api
    ports:
      - "8080:80"
    depends_on:
      - sge.postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=sge.postgres;Database=sgedb;Username=sgeuser;Password=sgepassword"
    networks:
      - sge_network

  sge.migrations:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: sge_migrations
    working_dir: /src
    volumes:
      - ./:/src
    depends_on:
      - sge.postgres
    environment:
      ConnectionStrings__DefaultConnection: "Host=sge.postgres;Database=sgedb;Username=sgeuser;Password=sgepassword"
    networks:
      - sge_network
    entrypoint: >
      bash -c "
        dotnet tool restore &&
        dotnet ef database update --project SGE.Infrastructure --startup-project SGE.API
      "

networks:
  sge_network:
    driver: bridge
