services:
  sge_postgres:
    image: postgres:latest
    container_name: sge_postgres
    environment:
      POSTGRES_DB: sgedb
      POSTGRES_USER: sgeuser
      POSTGRES_PASSWORD: sgepassword
    ports:
      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
    networks:
      - sge_network

  sge_api:
    build:
      context: .
      dockerfile: ./SGE.API/Dockerfile
    container_name: sge_api
    image: sge_api
    ports:
      - "8080:80"
    depends_on:
      - sge_postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=sge_postgres;Database=sgedb;Username=sgeuser;Password=sgepassword"
    networks:
      - sge_network

#volumes:
#  postgres_data:
#    driver: local

networks:
  sge_network:
    driver: bridge
